export PACKAGES=(
	ly
	niri
	noctalia-shell
	ghostty
	zsh
	startship
	helix
	uv
	yazi
	file
	ffmpeg
	7zip
	jq
	fd
	rg
	fzf
	zoxide
	resvg
	poppler
	imagemagick
	wl-clipboard
	docker
	git
	lazydocker
	lazygit
	tmux
)

export UV_TOOLS=(
	ruff
	basedpyright
	ty
)
