export PACKAGES=(
	sddm
	niri
	noctalia-shell
	ttf-cascadia-code-nerd
	ttf-cascadia-mono-nerd
	ghostty
	zsh
	starship
	helix
	uv
	yazi
	file
	ffmpeg
	7zip
	jq
	fd
	ripgrep
	fzf
	zoxide
	resvg
	poppler
	imagemagick
	wl-clipboard
	docker
	lazydocker
	lazygit
	tmux
	unzip
	rustup
	steam
	xwayland-satellite
	noto-fonts-cjk
	firefox
	bottom
	github-cli
	qt6-svg
	qt6-declarative
	qt5-quickcontrols2
)
