export PACKAGES=(
	ly
	niri
	noctalia-shell
	ttf-cascadia-code-nerd
	ttf-cascadia-mono-nerd
	ghostty
	zsh
	starship
	helix
	uv
	yazi
	file
	ffmpeg
	7zip
	jq
	fd
	ripgrep
	fzf
	zoxide
	resvg
	poppler
	imagemagick
	wl-clipboard
	docker
	lazydocker
	lazygit
	tmux
	unzip
	rustup
)
